# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: /linkhome/rech/genlig01/umz16dj/experiments/fairseq_tensorboard/pantagruel/base_10h_reproduce_torch2sdpa_stable_adam
  time_limit: 1190
  fp16_no_flatten_grads: true

checkpoint:
  # save_interval: 50
  save_interval_updates: 10000
  keep_interval_updates: 1
  # no_epoch_checkpoints: true
  best_checkpoint_metric: wer
  keep_best_checkpoints: 10
  keep_last_epochs: 20
  # patience: 10
  save_dir: /linkhome/rech/genlig01/umz16dj/experiments/fairseq_checkpoints/pantagruel/base_10h_reproduce_torch2sdpa_stable_adam

task:
  _name: audio_finetuning
  data: ???
  normalize: true
  labels: ltr

dataset:
  num_workers: 6
  max_tokens: 3200000
  skip_invalid_size_inputs_valid_test: true
  # validate_after_updates: 10000
  # validate_interval: 50
  # valid_subset: dev_other
  valid_subset: dev-other
  train_subset: train-labelled-10h

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 2

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 20000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08
  fused: true

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: /gpfsscratch/rech/ahm/umz16dj/Experiments/fairseq_checkpoints/pantagruel/base_audio_only_task_ngpu16_reproduce_en_torch2sdpa_stable/checkpoint_best.pt
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.05
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000
